# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'Demo' do

pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git', :tag => 'v0.9.3-lib'
pod 'GDJson', :git => 'https://github.com/goodow/GDJson.git'

pod 'GDChannel', :path => '..'

end

target 'DemoTests' do

end